### ISSUE TITLE
Write Now! #4

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#10]
### Value Proposition

As a hobby writer I want a warning if I save a draft under a name that is already used, so I dont overwrite existing documents on accident

### Acceptance Criteria

- [ ] If a draft is saved under an already existing name a warning should appear reading "There already exists a draft called ${draftname}. Are you sure you want to overwrite ist?"
- [ ] The user should see what names are already used
- [ ] if the user changes the draft name to a different draft name, that is also already in use the warning should reflect that

### Tasks

- [ ] create a new branch
- [ ] create a function that checks if a draft is already saved under that name
- [ ] if yes there should be a popup warning the user
- [ ] the popup should have the options "save anyway", "change name" and "abort"
- [ ] upon "change name" the user should see what names are already used

### Sizing/Complexity

L
