### ISSUE TITLE
Write Now! #5

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#11]
### Value Proposition

As a hobby writer I want to keep track of how many words I write in a session.

### Acceptance Criteria

- [ ] After closing a draft the user should get a popup informing them how many words they wrote in that session

### Tasks

- [ ] branch new create a
- [ ] app need to know how many words are in a document
- [ ] app needs to count words if document is saved
- [ ] app needs to compare the two numbers
- [ ] upon closing document app needs to display how many words were written that day

### Sizing/Complexity

 M
