### ISSUE TITLE
Write Now! #6

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#14]
### Value Proposition

As user I want my app to have a clean design so the other kids at starbucks dont make fun of me anymore 

### Description

Implement CSS styles for components and elements
![load functionality](https://user-images.githubusercontent.com/114575768/205018741-a860dbf8-e0bc-4b37-b664-3a3bd19263f5.png)

### Acceptance Criteria

- [ ] Buttons are styled
- [ ] Editor field is aligned in flex

### Tasks

- [ ] create new branch
- [ ] write test to check if elements are styled
- [ ] style buttons 
- [ ] style elements
- [ ] create pull request

### Sizing/Complexity

**S / M / L**

**Comment by SirJohn42Walker** [comment]
Well, the other kids at starbucks are certainly gonna make fun of you if can't decide on a sizing for your user stories... But aside from that seems good!

**Comment by SirJohn42Walker** [comment]
You have always been popular - To me! ;-)
