### ISSUE TITLE
Write Now! Set Goals

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#17]
### Value Proposition

**As a**  hobby writer **I need** to be able to set times for writing and a daily word goals
**to be able to** develop a writing habit.

### Description

![set goals](https://user-images.githubusercontent.com/114575768/205301985-70c80e53-e8e8-488f-8e40-641c5e90a1d9.png)

### Acceptance Criteria

- [ ] It should be possible to select multiple days for writing
- [ ] upon clicking on the `+`symbol a module should appear that allows to enter times
- [ ] clicking the '+' on a not activated weekday should activate that day
- [ ] it should be possible to have several writing times on the same day
- [ ] able to set daily word goals
- [ ] weekly word goal is equal to daily goal x activated weekdays

### Tasks

- [ ] create new branch
- [ ] create input field for word goal
- [ ] create radio buttons for selecting days to work
- [ ] create input to set times for writing
- [ ] times and word count should be remembered
- [ ] style all components
- [ ] go to quality assurance

### Sizing/Complexity

L
