### ISSUE TITLE
Write Now! Connect to MongoDB

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#21]
### Value Proposition

**As a** hobby writer 
**I need** to access my work from different devices
**to be able to** write where and when the opportunity presents itself

### Description

Connect the app to a database so works can be accessed and worked from different devices.

### Acceptance Criteria

- [ ] Website is connected to a database
- [ ] upon opening the link on a different device I can access and write the existing projects

### Tasks

- [ ] open an new branch
- [ ] set up a MongoDB
- [ ] fetch data from the DB
- [ ] implement way to add new data to DB
- [ ] implement way to manipulate data on DB
- [ ] implement way to delete data from DB
- [ ] go to code review
- [ ] go to quality assurance

### Sizing/Complexity

L
