### ISSUE TITLE
Wrtie Now! Save and delete function

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#22]
### Value Proposition

**As a** hobby writer **I need** a way to save my stories
**to be able to** make meaningful progress on them

### Description

Implement function to save and load stories from local storage

### Acceptance Criteria

- [ ] upon first opening "projects" should be empty
- [ ] upon further openings "projects" should show saved stories
- [ ] It should be possible to overwrite stories that have the same name
- [ ] it should be possible to delete stories

### Tasks

- [ ] create new branch
- [ ] create a local storage save and load functionality
- [ ] create a delete functionality on the elements of the "projects" page
- [ ] if user wants to save a story with an already existing name, he should be able to overwrite the older story.
- [ ] go to code review
- [ ] go to quality assurance

### Sizing/Complexity

 **M**
