### ISSUE TITLE
Write Now! Set Progress Mechanic

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#23]
### Value Proposition

**As a** hobby writer 
**I need** to keep track if my daily writing goals are met
**to be able to** improve my writing habit.

### Description

Add functionality to the "set Goals" page, that checks if the user actually wrote something in the set times and if the user has met its daily writing goals. 

### Acceptance Criteria

- [ ] A user should be able to set its daily writing goals and writing times.
- [ ] This should be stored in local storage
- [ ] The system should track if the times and writing goals are met
- [ ] The writing goals should count the combined progress in different documents (150 words in document A and 150 in document B should be counted 300 words written in total)

### Tasks

- [ ] create a new branch 
- [ ] create a variable that remembers the set writing progress
- [ ] create a variable that remembers the set writing times
- [ ] create a method to check if set goals are met
- [ ] go to code review
- [ ] go to quality assurance

### Sizing/Complexity

**L**
