### ISSUE TITLE
Write Now! Night mode

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#26]
### Value Proposition

**As a** hobby writer 
**I need** to be able to switch my settings into night mode
**to be able to** work on my projects without hurting my eyes

### Description

Implement switch in the navbar that sets things into night mode. 

### Acceptance Criteria

- [ ] switch in navbar that allows nightmode to be toggled on or off
- [ ] setting should be remembered upon reloading

### Tasks

(for developers team)

- [ ] create new branch
- [ ] create nightmode button in navbar
- [ ] create nightmode design pattern
- [ ] remember nightmode in local storage
- [ ] go to code review
- [ ] got to quallity assurance

### Sizing/Complexity

**S**
