### ISSUE TITLE
Write Now! Progress Bar

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#28]
### Value Proposition

**As a** hobby writer  **I need** visual feedback if I reach  my goal
**in order to be** motivated
### Description

Upon saving and closing a text there should be an progress bar. The length of the progress bar should be in relation to the set writing goal, with the progress bar exceeding past its boundaries if the user wrote more than planed. There should be a little celebratory animation if the user meets their goal.

### Acceptance Criteria

- [ ] upon saving a progress bar should appear and fill up
- [ ] if the bar meets the set goal a small animation should appear

### Tasks

- [ ] create new branch
- [ ] implement a progress bar in the closing popup
- [ ] write a function determining the size of the progress bar
- [ ] implement a celebratory animation upon reaching the set goal
- [ ] go to code review
- [ ] go to quality assurance

### Sizing/Complexity

** M **
