### ISSUE TITLE
Write Now! Design update

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#29]
### Value Proposition

**As a** user **I need** my app to look professional
**to be able to** trust it

### Description

Implement the established design rules over the whole app and clean up code at the same time

### Acceptance Criteria

- [ ] Background fills whole screen
- [ ] all buttons are variants of the same desing
- [ ] All elements are spaced nicely

### Tasks

- [ ] make new branch
- [ ] clean up desing
- [ ] clean up code
- [ ] go to review
- [ ] got to qa

### Sizing/Complexity

**M**
