### ISSUE TITLE
Write Now! Sort entries

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#30]
### Value Proposition

**As a** user **I need** to be able to find projects I worked on
**to be able to** work more eficiently

### Description

Saved documents should be able to searched for title or sorted by date, word count or alphabetically.

### Acceptance Criteria

- [ ] Option to sort or search "my projects" and "progress"

### Tasks

- [ ] create new branch
- [ ] create dropdown menue to search by criteria
- [ ] create mechanic to search for name
- [ ] go to code rewiew
- [ ] go to qa

### Sizing/Complexity

**M**
