### ISSUE TITLE
Write now! 2

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#4]
As a hobby writer I need to be able to write on several different projects at the same time.

### Description

Make it possible to have several different text documents in local storage at the same time

### Tasks

- [ ] create surface from where different documents can be accessed
- [ ] implement options to create a new document and delete unwanted documents
- [ ] allow for several different documents to be saved in local storage

### Sizing/Complexity

**S / M / L**
