### ISSUE TITLE
Write now! 3

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#5]
As a hobby writer I want to see how many words I wrote on a day in order to form a writing habbit.

### Acceptance Criteria

- [ ] word count should only be shown if number is positive. Deletions of previous text should not count

### Tasks

(for developers team)

- [ ] site should remember word count of a document once it is opend
- [ ] when document is closed again it should count words again
- [ ] should compare the two numbers and give back the difference

### Sizing/Complexity

**S / M / L**
