### ISSUE TITLE
Write now! 4

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#6]
As a hobby writer I want to set my daily and weekly goals for writing in order to keep myself accountable.

### Tasks

- [ ] set up subpage that allows to set daily and weekly word-count
- [ ] If a document is closed page should check how much of the daily and weekly word-counts are achieved
- [ ] results should be visualised

### Sizing/Complexity

**S / M / L**
