### ISSUE TITLE
Write now! 5

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#7]
As a hobby writer I need my app to have a nice design.

### Tasks

- [ ] brainstorm a good name
- [ ] design the basic components
- [ ] design the rest

### Sizing/Complexity

**S / M / L**
