### ISSUE TITLE
Write Now! #2

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#8]
### Value Proposition

As a user I want my tool to have several functionality that I need to access

### Description

Create the navigation element

### Acceptance Criteria

- [ ] Site should have a navigation element. It does not need to link to anything
- [ ] The navigation element should include "projects", "progress" and "set goals"

### Tasks

- [ ] create a new branch
- [ ] create a navigation element
- [ ] it should contain the options "projects", "progress" and "set goals"
- [ ] subsites do not need to exist right now.

### Sizing/Complexity

M
