### ISSUE TITLE
Write Now! #3

### ISSUE THREAD

**Issue by Timo-Thees** [Timo-Thees/Capstone#9]
### Value Proposition

As a hobby writer I need to be able to load saved documents in order to work on them again

### Description

Scribble / design or text

### Acceptance Criteria

- [ ] There should be a load button
- [ ] pressing the load button lets you see the different documents saved
- [ ] on choosing a document to load the app should switch to the text editor and load the text in there

### Tasks

(for developers team)

- [ ] create new branch
- [ ] create new component that lists saved documents by name
- [ ] on click switch to editor
- [ ] load text into editor

### Sizing/Complexity

L
